title: Sabina Rovansek - UX Designer
description: Portfolio website for UX designer Sabina Rovansek
url: https://chottobina.github.io
baseurl: ""

# Build settings
markdown: kramdown

# Include static files
include:
  - assets

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
